"""Generated by Genrepo

Auto-generated repository for User (SQLModel).
"""

from __future__ import annotations

from typing import Optional, Any

from sqlmodel import Session, select
from sqlalchemy import func

from app.models.user import User


class UserRepository:
    """Repository for User.

    Generated CRUD methods are controlled by configuration. Methods follow
    simple defaults and are intended as a starting point.
    """

    class NotFoundError(Exception):
        """Raised when an entity is not found."""

    def get(self, session: Session, id: int) -> Optional[User]:
        """Return a single User by primary key or None."""
        stmt = select(User).where(getattr(User, "id") == id)
        return session.exec(stmt).first()

    def get_or_raise(self, session: Session, id: int) -> User:
        """Return a single User by PK or raise NotFoundError."""
        obj = self.get(session, id)
        if obj is None:
            raise self.NotFoundError(f"User not found: {id}")
        return obj

    def list(self, session: Session, *where, limit: int = 100, offset: int = 0) -> list[User]:
        """Return many User with pagination and optional filters."""
        stmt = select(User)
        if where:
            stmt = stmt.where(*where)
        stmt = stmt.offset(offset).limit(limit)
        return list(session.exec(stmt).all())

    def find_one(self, session: Session, *where) -> Optional[User]:
        """Return the first User matching filters or None."""
        stmt = select(User)
        if where:
            stmt = stmt.where(*where)
        return session.exec(stmt).first()

    def create(self, session: Session, obj_in: User) -> User:
        """Persist a new User and refresh before returning."""
        session.add(obj_in)
        session.commit()
        session.refresh(obj_in)
        return obj_in

    def update(self, session: Session, db_obj: User, obj_in: dict[str, Any]) -> User:
        """Update an existing User with provided fields and refresh."""
        for k, v in obj_in.items():
            setattr(db_obj, k, v)
        session.add(db_obj)
        session.commit()
        session.refresh(db_obj)
        return db_obj

    def delete(self, session: Session, db_obj: User) -> None:
        """Delete a User instance."""
        session.delete(db_obj)
        session.commit()

    def delete_by_id(self, session: Session, id: int) -> bool:
        """Delete by PK and return True if removed."""
        obj = self.get(session, id)
        if not obj:
            return False
        session.delete(obj)
        session.commit()
        return True

    def exists(self, session: Session, *where) -> bool:
        """Return True if any row matches filters."""
        stmt = select(User)
        if where:
            stmt = stmt.where(*where)
        return session.exec(stmt.limit(1)).first() is not None

    def count(self, session: Session, *where) -> int:
        """Return the number of rows matching filters."""
        stmt = select(func.count()).select_from(User)
        if where:
            stmt = stmt.where(*where)
        return int(session.exec(stmt).scalar_one())
